//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Scripts/Input.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Input : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Input()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Input"",
    ""maps"": [
        {
            ""name"": ""toothBrushMap"",
            ""id"": ""2e6baac2-683e-4e2b-aa4f-8ce977a6ac55"",
            ""actions"": [
                {
                    ""name"": ""Mouse"",
                    ""type"": ""Value"",
                    ""id"": ""fbfe84e3-d325-4b9e-ae61-78a23e495424"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Click"",
                    ""type"": ""Button"",
                    ""id"": ""942ed8fd-fc2d-4fcc-a6ed-7d0a314e38b3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c2d466a5-c7a7-4ddd-a727-0df61de118fe"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": ""ScaleVector2"",
                    ""groups"": """",
                    ""action"": ""Mouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""33d0f590-9e80-45ca-915e-b08336b3ef5a"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // toothBrushMap
        m_toothBrushMap = asset.FindActionMap("toothBrushMap", throwIfNotFound: true);
        m_toothBrushMap_Mouse = m_toothBrushMap.FindAction("Mouse", throwIfNotFound: true);
        m_toothBrushMap_Click = m_toothBrushMap.FindAction("Click", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // toothBrushMap
    private readonly InputActionMap m_toothBrushMap;
    private IToothBrushMapActions m_ToothBrushMapActionsCallbackInterface;
    private readonly InputAction m_toothBrushMap_Mouse;
    private readonly InputAction m_toothBrushMap_Click;
    public struct ToothBrushMapActions
    {
        private @Input m_Wrapper;
        public ToothBrushMapActions(@Input wrapper) { m_Wrapper = wrapper; }
        public InputAction @Mouse => m_Wrapper.m_toothBrushMap_Mouse;
        public InputAction @Click => m_Wrapper.m_toothBrushMap_Click;
        public InputActionMap Get() { return m_Wrapper.m_toothBrushMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ToothBrushMapActions set) { return set.Get(); }
        public void SetCallbacks(IToothBrushMapActions instance)
        {
            if (m_Wrapper.m_ToothBrushMapActionsCallbackInterface != null)
            {
                @Mouse.started -= m_Wrapper.m_ToothBrushMapActionsCallbackInterface.OnMouse;
                @Mouse.performed -= m_Wrapper.m_ToothBrushMapActionsCallbackInterface.OnMouse;
                @Mouse.canceled -= m_Wrapper.m_ToothBrushMapActionsCallbackInterface.OnMouse;
                @Click.started -= m_Wrapper.m_ToothBrushMapActionsCallbackInterface.OnClick;
                @Click.performed -= m_Wrapper.m_ToothBrushMapActionsCallbackInterface.OnClick;
                @Click.canceled -= m_Wrapper.m_ToothBrushMapActionsCallbackInterface.OnClick;
            }
            m_Wrapper.m_ToothBrushMapActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Mouse.started += instance.OnMouse;
                @Mouse.performed += instance.OnMouse;
                @Mouse.canceled += instance.OnMouse;
                @Click.started += instance.OnClick;
                @Click.performed += instance.OnClick;
                @Click.canceled += instance.OnClick;
            }
        }
    }
    public ToothBrushMapActions @toothBrushMap => new ToothBrushMapActions(this);
    public interface IToothBrushMapActions
    {
        void OnMouse(InputAction.CallbackContext context);
        void OnClick(InputAction.CallbackContext context);
    }
}
